"""Cop protocol boundary; transport behavior is intentionally absent."""

from p2p_cop_agent.protocol.attestation import (
    AttestationError,
    HostSpec,
    SealedAttestation,
    attestation_wire,
    build_step_zero,
    review_opponent_attestation,
    running_git_commit,
    seal_step_zero,
    verify_attestation,
)
from p2p_cop_agent.protocol.audit import (
    AuditReport,
    AuditVerdict,
    audit_reveal,
)
from p2p_cop_agent.protocol.commit import (
    CommitError,
    canonical_payload_bytes,
    generate_commitment_nonce,
    move_commit,
    verify_commit,
)
from p2p_cop_agent.protocol.commit_reveal import (
    CommitRevealError,
    SealedTurn,
    TurnLedger,
    verify_audit,
)
from p2p_cop_agent.protocol.declaration import (
    DeclarationError,
    build_declaration,
    lock_declaration,
)
from p2p_cop_agent.protocol.identity import (
    MANDATORY_IDENTITY,
    IdentityError,
    build_identity,
    require_complete_identity,
)
from p2p_cop_agent.protocol.messages import (
    MESSAGE_SCHEMAS,
    OK_RESPONSE,
    REFUSAL_WORDS,
    WIRE_ROLES,
    ProtocolError,
    is_acknowledgement,
    is_ok_response,
    require_wire_role,
    signals_refusal,
    validate_message,
)
from p2p_cop_agent.protocol.negotiation import (
    FIXED_TERMS,
    MINIMUM_TERMS,
    NegotiationError,
    build_offer,
    check_appendix_f,
    terms_from_config,
    validate_participants,
)
from p2p_cop_agent.protocol.offer_review import verify_offer
from p2p_cop_agent.protocol.receive import (
    ConflictError,
    Intake,
    ReplayError,
    TurnInbox,
)
from p2p_cop_agent.protocol.scent_wire import (
    WIRE_PRECISION,
    ScentWireError,
    decode_scent,
    encode_scent,
    saturation_limit,
)

__all__ = [
    "FIXED_TERMS",
    "MANDATORY_IDENTITY",
    "MESSAGE_SCHEMAS",
    "MINIMUM_TERMS",
    "OK_RESPONSE",
    "WIRE_PRECISION",
    "ScentWireError",
    "decode_scent",
    "encode_scent",
    "saturation_limit",
    "REFUSAL_WORDS",
    "WIRE_ROLES",
    "IdentityError",
    "NegotiationError",
    "build_identity",
    "build_offer",
    "require_complete_identity",
    "check_appendix_f",
    "terms_from_config",
    "validate_participants",
    "verify_offer",
    "AttestationError",
    "AuditReport",
    "AuditVerdict",
    "CommitError",
    "CommitRevealError",
    "ConflictError",
    "DeclarationError",
    "HostSpec",
    "Intake",
    "ProtocolError",
    "ReplayError",
    "SealedAttestation",
    "SealedTurn",
    "TurnInbox",
    "TurnLedger",
    "attestation_wire",
    "audit_reveal",
    "build_declaration",
    "build_step_zero",
    "lock_declaration",
    "review_opponent_attestation",
    "canonical_payload_bytes",
    "generate_commitment_nonce",
    "is_acknowledgement",
    "is_ok_response",
    "move_commit",
    "require_wire_role",
    "running_git_commit",
    "seal_step_zero",
    "signals_refusal",
    "validate_message",
    "verify_attestation",
    "verify_audit",
    "verify_commit",
]
